### ISSUE TITLE
Won't class implememts protocol more type friendly and easy to init?

### ISSUE THREAD

**Issue by LongTengDao** [tc39/proposal-first-class-protocols#42]
Currently, I see it's:

```
protocol ToString {
    tag;
    toString () {
        return `[object ${this[ToString.tag]}]`;
    }
}

Object.prototype[ToString.tag] = 'Object';
Protocol.implement(Object, ToString);
```

Why not like this:

```
protocol ToString {
    tag;
    toString () {
        return `[object ${this[ToString.tag]}]`;
    }
}

Object implements ToString {
    tag = 'Object';
}
```

**Comment by michaelficarra** [comment]
There's 3 different cases for protocol implementation:

1. You are defining the protocol but do not own the class. We have a form for this:

    ```js
    protocol Foldable {
    
      // ...
    
      implemented by Array {
        foldr(f, memo) {
          // implementation elided
        }
      }
    }
    ```

1. You are defining the class but do not own the protocol. We have a form for this:

    ```js
    class NEList {
      constructor(head, tail) {
        this.head = head;
        this.tail = tail;
      }
    
      implements protocol Foldable {
        foldr(f, memo) {
          // implementation elided
        }
      }
    }
    ```

1. You own neither the protocol nor the class. This is an antipattern ([orphan instance](https://wiki.haskell.org/Orphan_instance)) that we want to discourage. There is no affordance for this. We want it to be possible but we do not want it to be convenient. `Protocol.implement` is sufficient.

Your example could use the first form.
